### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by SteveJSzabo** [a-busman/DigitalFoundryUpdater#1]
**Describe the bug**
When trying to run the code, it successfully asks for the download location but fails when attempting to get the cookie from chrome.

**To Reproduce**
Configuration is set to use chrome and no twilio config is used. When running, I get the following (note the Python folder location has been edited to remove user-specific data):
Traceback (most recent call last):
  File "E:\GIT\DigitalFoundryUpdater\main.py", line 108, in <module>
    main()
  File "E:\GIT\DigitalFoundryUpdater\main.py", line 64, in main
    downloader = Downloader(browser, sid, token, to, from_, output_path)
  File "E:\GIT\DigitalFoundryUpdater\downloader.py", line 67, in init
    self.load_cookie_jar()
  File "E:\GIT\DigitalFoundryUpdater\downloader.py", line 74, in load_cookie_jar
    self.cj = chrome()
  File "Python39\lib\site-packages\browsercookie__init.py", line 397, in chrome
    return Chrome(cookie_file).load()
  File "Python39\lib\site-packages\browsercookie__init.py", line 87, in load
    for cookie in self.get_cookies():
  File "Python39\lib\site-packages\browsercookie__init.py", line 149, in get_cookies
    value = self._decrypt(item[5], item[6], key=key)
  File "Python39\lib\site-packages\browsercookie__init__.py", line 183, in _decrypt
    return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode("utf-8")
pywintypes.error: (87, 'CryptProtectData', 'The parameter is incorrect.')

**Expected behavior**
The cookie is loaded and the site is scraped and videos downloaded.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
The following libraries were installed with pip in order to get this far:
 - Downloader
 - browsercookie
 - twilio
 - toml
 - pypiwin32

**Comment by a-busman** [comment]
Looks like an issue in `browsercookie` somewhere. Will try to see exactly what's going on.

**Comment by a-busman** [comment]
Which version of `browsercookie` are you using?

**Comment by a-busman** [comment]
It appears that `browsercookie` had an update https://github.com/richardpenman/browsercookie/commit/864474403610fd15ff576615a6e0d603c7263f6e which apparently fixes Chrome 80+ support.

I'd suggest doing a `pip install browsercookie --upgrade`.

**Comment by SteveJSzabo** [comment]
After installing the updated browsercookie, I'm able to get further, but still have an error:
Traceback (most recent call last):
  File "E:\GIT\DigitalFoundryUpdater\main.py", line 108, in <module>
    main()
  File "E:\GIT\DigitalFoundryUpdater\main.py", line 64, in main
    downloader = Downloader(browser, sid, token, to, from_, output_path)
  File "E:\GIT\DigitalFoundryUpdater\downloader.py", line 104, in __init__
    self.__load_cookie_jar()
  File "E:\GIT\DigitalFoundryUpdater\downloader.py", line 111, in __load_cookie_jar
    self.__cj = chrome()
  File "C:\Users\doste\AppData\Local\Programs\Python\Python39\lib\site-packages\browsercookie\__init__.py", line 397, in chrome
    return Chrome(cookie_file).load()
  File "C:\Users\doste\AppData\Local\Programs\Python\Python39\lib\site-packages\browsercookie\__init__.py", line 87, in load
    for cookie in self.get_cookies():
  File "C:\Users\doste\AppData\Local\Programs\Python\Python39\lib\site-packages\browsercookie\__init__.py", line 149, in get_cookies
    value = self._decrypt(item[5], item[6], key=key)
  File "C:\Users\doste\AppData\Local\Programs\Python\Python39\lib\site-packages\browsercookie\__init__.py", line 183, in _decrypt
    return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode("utf-8")
pywintypes.error: (87, 'CryptProtectData', 'The parameter is incorrect.')

**Comment by SteveJSzabo** [comment]
Another note is that the requirement for win32crypt (as required by browsercookie) I satisfied by installing pypiwin32 (pip install pypiwin32). If this isn't the expected library, I imagine that would cause this failure here.

**Comment by a-busman** [comment]
Can you try uninstalling your version of `browsercookie`, and installing the latest from the repo?

```sh
$ pip uninstall browsercookie
$ pip install https://github.com/richardpenman/browsercookie/archive/master.zip
```

**Comment by SteveJSzabo** [comment]
That worked! Weird, but I'll take it!

**Comment by SteveJSzabo** [comment]
Looks like browsercookie is broken again (I updated an issue in that repo) with the latest Chrome update (90.0.4430.93).

https://github.com/richardpenman/browsercookie/issues/7#issuecomment-829501205

**Comment by a-busman** [comment]
@SteveJSzabo it appears as though browsercookie has remedied this issue. I've updated the `requirements.txt` in 90a121593b80d153c2ed25867f3ab6961a777830 to include the latest.
